###练习
'''
某城市一周的最高气温为[28,30,29,31,32,30,29]
计算平均气温，最高气温，最低气温
找出气温超过30°的天气
'''

In [17]:
import numpy as np
temps = np.array([28,30,29,31,32,30,29])
print(temps)
print("平均气温:",'%.2f'%np.mean(temps))
print("最高气温:",np.max(temps))
print("最低气温:",np.min(temps))
print("超过30°的天气",np.cumsum(np.where(temps>30,1,0))[-1])

[28 30 29 31 32 30 29]
平均气温: 29.86
最高气温: 32
最低气温: 28
超过30°的天气 2


题目2 学生成绩统计
某班级5名同学成绩[85,91,78,91,88]
计算成绩平均分，中位数和标准差
将成绩转化为百分制（假设为10分）

In [23]:
score = np.array([85,91,78,91,88])
print("平均分：",np.mean(score))
print("中位数：",np.median(score))
print("标准差：",np.std(score))
print("标准差：",score/100)

平均分： 86.6
中位数： 88.0
标准差： 4.841487374764082
标准差： [0.85 0.91 0.78 0.91 0.88]


矩阵计算
A矩阵=[[1,2],[3,4]] B=[[5,6],[7,8]]
计算A+B A*B
计算A和B矩阵乘法点积

In [26]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


随机数据生成
生成一个（3，4）的随机整数数组，范围[0,10)
计算每列的最大值和每行的最小值
将数组中的所有奇数替换成-1

In [44]:
np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print(arr)
print('每列的最大值：',np.max(arr,axis=0))#axis=0 是列 1是行
print('每行的最小值：',np.min(arr,axis=1))#axis=0 是列 1是行
print(np.where(arr%2==1,-1,arr))
arr[arr%2==1]=-1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值： [7 9 7 6]
每行的最小值： [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


数组变形
创建一个1-12的以维数组，并转换为（3，4）的二维数组
计算每行和每列的平均值
将数组展平为一维数组

In [56]:
arr = np.arange(1,13)
print(arr)
print(np.reshape(arr,(3,4)))
arr =np.reshape(arr,(3,4))
print("每行的和",np.sum(arr,axis=1))
print("每列的平均值",np.mean(arr,axis=0))
print(np.reshape(arr,(12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和 [10 26 42]
每列的平均值 [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


生成一个（5，5）的随机数组 范围[0,20)
找出数组中大于10的元素
将所有大于10的元素替换为0

In [62]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr)
print('大于10的元素',arr[arr>10])
print('大于10的元素替换0',np.where([arr>10],0,arr))

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
大于10的元素 [12 15 19 18 12 14 17 13 19 16 19]
大于10的元素替换0 [[[0 0 0 3 3]
  [7 9 0 0 4]
  [6 0 1 6 7]
  [0 0 5 0 8]
  [9 0 0 0 5]]]


统计函数应用
莫公司6个月的销售额为[120,135,110,125,130,140]
计算总销售额，均值，方差
找出销售额最高和最低的月份

In [69]:
arr=np.array([120,135,110,125,130,140])
print('总销售额：',np.sum(arr))
print('均值：',np.mean(arr))
print('方差：',np.var(arr))
print('最高的月份：',np.argmax(arr)+1) #arg找到索引
print('最高的月份：',np.argmin(arr)+1)

总销售额： 760
均值： 126.66666666666667
方差： 97.22222222222223
最高的月份： 6
最高的月份： 3


8.数组拼接
A=[1,2,3] B=[4,5,6]
将A和B水平拼接成一个新的数组
将A和B垂直拼接成一个新的数组

In [72]:
A=np.array([1,2,3])
B=np.array([4,5,6])
C=np.concatenate([A,B])
print(C)
print(np.reshape(C,(2,3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


唯一值和排序
数组[2,1,2,3,1,4,3]
找出数组中的唯一值并排序
计算每一个唯一值出现的次数

In [78]:
arr=np.array([2,1,2,3,1,4,3])
u_arr,count=np.unique(arr,return_counts=True)
print(u_arr)
print(count)
d= []
for i in range(len(u_arr)):
    d = d + [len(arr[arr==u_arr[i]])]
print(d)

[1 2 3 4]
[2 2 2 1]
[2, 2, 2, 1]


综合练习
销售额：[20,25,22,30,28]
成本：[15,18,16,22,20]
计算每天的利润
计算利润的平均值和标准差
找出利润最高的天数

In [88]:
moneny = np.array([20,25,22,30,28])
cb = np.array([15,18,16,22,20])
cost  = moneny-cb
print('利润:',cost)
print('平均:',np.mean(cost))
print('标准差:',np.std(cost))
print('最高的天数:',len(cost[cost==np.max(cost)]))

利润: [5 7 6 8 8]
平均: 6.8
标准差: 1.16619037896906
最高的天数: 2
